# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from qdarkstyle import load_stylesheet
import sys
from PyQt5.QtCore import Qt
import vtkmodules.all as vtk
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from vtkmodules.vtkCommonColor import vtkNamedColors
from vtkmodules.vtkRenderingCore import (
    vtkColorTransferFunction,
    vtkRenderer,
    vtkVolume,
    vtkVolumeProperty
)


class Ui_MainWindow(object):
    def __initWidget(self):
        """ 初始化小部件 """

        # 隐藏滚动条
        self.view1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        # 以鼠标所在位置为锚点进行缩放
        self.view1.setTransformationAnchor(self.view1.AnchorUnderMouse)
        self.view2.setTransformationAnchor(self.view2.AnchorUnderMouse)
        self.view3.setTransformationAnchor(self.view3.AnchorUnderMouse)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1670, 860)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # QGraphicsScene
        self.scene1 = QtWidgets.QGraphicsScene(self.centralwidget)  # show picture
        self.view1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view1.setMouseTracking(True)
        self.view1.setScene(self.scene1)
        self._color_background = QtGui.QColor('#000000')
        self.scene1.setBackgroundBrush(self._color_background)
        self.view1.setSceneRect(0, 0, 400, 340)
        self.view1.setGeometry(QtCore.QRect(440, 51, 406, 346))
        self.view1.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.scene2 = QtWidgets.QGraphicsScene(self.centralwidget)
        self.view2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view2.setMouseTracking(True)
        # self.setCentralWidget(self.centralwidget)
        # 有view就要有scene
        self.view2.setScene(self.scene2)
        self._color_background = QtGui.QColor('#000000')
        self.scene2.setBackgroundBrush(self._color_background)
        self.view2.setSceneRect(0, 0, 400, 340)
        self.view2.setGeometry(QtCore.QRect(440, 431, 406, 346))
        self.view2.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.scene3 = QtWidgets.QGraphicsScene(self.centralwidget)
        self.view3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view3.setMouseTracking(True)
        # self.setCentralWidget(self.centralwidget)
        # 有view就要有scene
        self.view3.setScene(self.scene3)
        self._color_background = QtGui.QColor('#000000')
        self.scene3.setBackgroundBrush(self._color_background)
        # self.view3.setSceneRect(0, 0, 500, 420)
        # self.view3.setGeometry(QtCore.QRect(529, 51, 506, 426))
        self.view3.setSceneRect(0, 0, 400, 340)
        #self.view3.setGeometry(QtCore.QRect(429, 51, 406, 346))
        self.view3.setGeometry(QtCore.QRect(860, 51, 406, 346))
        self.view3.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.__initWidget()

        self.menubar = QtWidgets.QMenuBar(self.centralwidget)
        # self.menubar.setGeometry(QtCore.QRect(2, 0, 1600, 38))
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_image = QtWidgets.QAction("Load and Display (&Image)", self.menubar)
        self.menu_image.setObjectName("menu_image")

        self.menu_seg = QtWidgets.QAction("Seg Results (&Mask)", self.menubar)
        self.menu_seg.setObjectName("menu_seg")

        self.menu_liverseg = QtWidgets.QAction("Liv and Spl Seg (&Liver and spleen)", self.menubar)
        self.menu_liverseg.setObjectName("menu_liverseg")

        self.menu_vascularseg = QtWidgets.QAction("Vas Seg (&Vascular)", self.menubar)
        self.menu_vascularseg.setObjectName("menu_vascularseg")

        self.menu_musfatseg = QtWidgets.QAction("Mus and Fat Seg (&Muscle and fat)", self.menubar)
        self.menu_musfatseg.setObjectName("menu_musfatseg")


        self.menubar.addAction(self.menu_image)
        # self.menubar.addMenu(self.menu_alternative)
        self.menubar.addAction(self.menu_liverseg)
        self.menubar.addAction(self.menu_vascularseg)
        self.menubar.addAction(self.menu_musfatseg)
        self.menubar.addAction(self.menu_seg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 43))
        

        # Status
        self.bound_stat = QtWidgets.QLabel(self.centralwidget)
        self.bound_stat.setGeometry(QtCore.QRect(0, 830, 2000, 40))
        self.bound_stat.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_stat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_stat.setFrameShape(QtWidgets.QFrame.Box)
     
        self.bound_stat.setObjectName("bound_stat")

        self.statusbar = QtWidgets.QStatusBar(self.centralwidget)
        
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.statusbar.setFont(font)
        # self.statusbar.setAlignment(QtCore.Qt.AlignCLeft)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.showMessage('Ready')
        self.statusbar.setGeometry(QtCore.QRect(0, 810, 2000, 50))
      

        # bound of Choose


        # bound of Preidct
        self.bound_predict = QtWidgets.QLabel(self.centralwidget)
        #self.bound_predict.setGeometry(QtCore.QRect(1500, 52, 390, 884))
        self.bound_predict.setGeometry(QtCore.QRect(1275, 52, 390, 738))
        self.bound_predict.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_predict.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_predict.setFont(font)
        self.bound_predict.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_predict.setObjectName("bound_predict")

        self.bound_predict2 = QtWidgets.QLabel(self.centralwidget)
        self.bound_predict2.setGeometry(QtCore.QRect(9, 52, 422, 738))
        self.bound_predict2.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_predict2.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict2.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_predict2.setFont(font)
        self.bound_predict2.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_predict2.setObjectName("bound_predict2")
     

        # bound of vface
        self.bound_vface = QtWidgets.QLabel(self.centralwidget)
        #self.bound_vface.setGeometry(QtCore.QRect(529, 511, 506, 426))
        
        self.bound_vface.setGeometry(QtCore.QRect(860, 431, 406, 346))
        self.bound_vface.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_vface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_vface.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_vface.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(0, 0, 0);')
        self.bound_vface.setObjectName("bound_vface")

        self.label_calRadiomics = QtWidgets.QLabel(self.centralwidget)
        self.label_calRadiomics.setGeometry(QtCore.QRect(1287, 102, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_calRadiomics.setFont(font)
        self.label_calRadiomics.setObjectName("label_calRadiomics")

        self.radiomics = QtWidgets.QPushButton(self.centralwidget)
        self.radiomics.setGeometry(QtCore.QRect(1540, 105, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.radiomics.setFont(font)
        self.radiomics.setObjectName("radiomics")

        self.label__1 = QtWidgets.QLabel(self.centralwidget)
        self.label__1.setGeometry(QtCore.QRect(1315, 140, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__1.setFont(font)
        self.label__1.setObjectName("label__1")

        self.loadcsv = QtWidgets.QPushButton(self.centralwidget)
        self.loadcsv.setGeometry(QtCore.QRect(1540, 143, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.loadcsv.setFont(font)
        self.loadcsv.setObjectName("loadcsv")

        self.label_b3 = QtWidgets.QLabel(self.centralwidget)
        self.label_b3.setGeometry(QtCore.QRect(1278, 180, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_b3.setFont(font)
        self.label_b3.setObjectName("label_b3")

        # Label " Load clinical factors"
        self.label_loadCli = QtWidgets.QLabel(self.centralwidget)
        self.label_loadCli.setGeometry(QtCore.QRect(1287, 210, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_loadCli.setFont(font)
        self.label_loadCli.setObjectName("label_loadCli")

        #Age:
        self.label__3 = QtWidgets.QLabel(self.centralwidget)
        self.label__3.setGeometry(QtCore.QRect(1305, 250, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__3.setFont(font)
        self.label__3.setObjectName("label__3")

        self.box1 = QtWidgets.QLineEdit(self.centralwidget)
        self.box1.setGeometry(QtCore.QRect(1495, 253, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.box1.setAlignment(Qt.AlignCenter)
        self.box1.setFont(font)
        self.box1.setObjectName("box1")


        self.label__4 = QtWidgets.QLabel(self.centralwidget)
        self.label__4.setGeometry(QtCore.QRect(1305, 305, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__4.setFont(font)
        self.label__4.setObjectName("label__4")

        self.box2 = QtWidgets.QLineEdit(self.centralwidget)
        self.box2.setGeometry(QtCore.QRect(1495, 308, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.box2.setAlignment(Qt.AlignCenter)
        self.box2.setFont(font)
        self.box2.setObjectName("box2")

        self.label__5 = QtWidgets.QLabel(self.centralwidget)
        self.label__5.setGeometry(QtCore.QRect(1305, 360, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__5.setFont(font)
        self.label__5.setObjectName("label__5")


        self.box3 = QtWidgets.QLineEdit(self.centralwidget)
        self.box3.setGeometry(QtCore.QRect(1495, 363, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.box3.setFont(font)
        self.box3.setAlignment(Qt.AlignCenter)
        self.box3.setObjectName("box3")


        self.label__6 = QtWidgets.QLabel(self.centralwidget)
        self.label__6.setGeometry(QtCore.QRect(1305, 415, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__6.setFont(font)
        self.label__6.setObjectName("label__6")

        self.box4 = QtWidgets.QLineEdit(self.centralwidget)
        self.box4.setGeometry(QtCore.QRect(1495, 418, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.box4.setAlignment(Qt.AlignCenter)
        self.box4.setFont(font)
        self.box4.setObjectName("box4")

        self.label__7 = QtWidgets.QLabel(self.centralwidget)
        self.label__7.setGeometry(QtCore.QRect(1305, 470, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label__7.setFont(font)
        self.label__7.setObjectName("label__7")

        self.box5 = QtWidgets.QLineEdit(self.centralwidget)
        self.box5.setGeometry(QtCore.QRect(1495, 473, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.box5.setAlignment(Qt.AlignCenter)
        self.box5.setFont(font)
        self.box5.setObjectName("box5")


        self.clincf_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.clincf_confirm.setGeometry(QtCore.QRect(1300, 530, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clincf_confirm.setFont(font)
        self.clincf_confirm.setObjectName("clincf_confirm")

        # Button "Clear factor"
        self.clearfactor = QtWidgets.QPushButton(self.centralwidget)
        self.clearfactor.setGeometry(QtCore.QRect(1520, 530, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clearfactor.setFont(font)
        self.clearfactor.setObjectName("clearfactor")

        self.label_b4 = QtWidgets.QLabel(self.centralwidget)
        self.label_b4.setGeometry(QtCore.QRect(1278, 585, 380, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_b4.setFont(font)
        self.label_b4.setObjectName("label_b4")

        # Button "Predict"
        self.predict = QtWidgets.QPushButton(self.centralwidget)
        self.predict.setGeometry(QtCore.QRect(1300, 625, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.predict.setFont(font)
        self.predict.setObjectName("predict")

        # Button "Clear all"
        self.clesarall = QtWidgets.QPushButton(self.centralwidget)
        self.clesarall.setGeometry(QtCore.QRect(1520, 625, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clesarall.setFont(font)
        self.clesarall.setObjectName("clesarall")

        self.label_loadLiver = QtWidgets.QLabel(self.centralwidget)
        self.label_loadLiver.setGeometry(QtCore.QRect(17, 102, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_loadLiver.setFont(font)
        self.label_loadLiver.setObjectName("label_loadLiver")

        self.loadlivmask = QtWidgets.QPushButton(self.centralwidget)
        self.loadlivmask.setGeometry(QtCore.QRect(330, 103, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.loadlivmask.setFont(font)
        self.loadlivmask.setObjectName("loadlivmask")

        self.cal_liv = QtWidgets.QPushButton(self.centralwidget)
        self.cal_liv.setGeometry(QtCore.QRect(330, 260, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.cal_liv.setFont(font)
        self.cal_liv.setObjectName("cal_liv")

        self.label_x10 = QtWidgets.QLabel(self.centralwidget)
        self.label_x10.setGeometry(QtCore.QRect(20, 140, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x10.setFont(font)
        self.label_x10.setObjectName("label_x10")
    
        self.label_x11 = QtWidgets.QLabel(self.centralwidget)
        self.label_x11.setGeometry(QtCore.QRect(210, 140, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x11.setFont(font)
        self.label_x11.setObjectName("label_x11")


        self.median_liv = QtWidgets.QTextBrowser(self.centralwidget)
        self.median_liv.setGeometry(QtCore.QRect(233, 137, 70, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.median_liv.setFont(font)
        self.median_liv.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.median_liv.setObjectName("median_liv")

        self.label_x12 = QtWidgets.QLabel(self.centralwidget)
        self.label_x12.setGeometry(QtCore.QRect(20, 180, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x12.setFont(font)
        self.label_x12.setObjectName("label_x12")

        self.label_x13 = QtWidgets.QLabel(self.centralwidget)
        self.label_x13.setGeometry(QtCore.QRect(210, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x13.setFont(font)
        self.label_x13.setObjectName("label_x13")

        self.median_spl = QtWidgets.QTextBrowser(self.centralwidget)
        self.median_spl.setGeometry(QtCore.QRect(233, 177, 70, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.median_spl.setFont(font)
        self.median_spl.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.median_spl.setObjectName("median_spl")

        self.label_x14 = QtWidgets.QLabel(self.centralwidget)
        self.label_x14.setGeometry(QtCore.QRect(20, 220, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x14.setFont(font)
        self.label_x14.setObjectName("label_x14")

        self.label_x15 = QtWidgets.QLabel(self.centralwidget)
        self.label_x15.setGeometry(QtCore.QRect(210, 220, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x15.setFont(font)
        self.label_x15.setObjectName("label_x15")

        self.IQ_liv = QtWidgets.QTextBrowser(self.centralwidget)
        self.IQ_liv.setGeometry(QtCore.QRect(233, 217, 60, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.IQ_liv.setFont(font)
        self.IQ_liv.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.IQ_liv.setObjectName("IQ_liv")

        self.label_x16 = QtWidgets.QLabel(self.centralwidget)
        self.label_x16.setGeometry(QtCore.QRect(20, 260, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x16.setFont(font)
        self.label_x16.setObjectName("label_x16")

        self.label_x17 = QtWidgets.QLabel(self.centralwidget)
        self.label_x17.setGeometry(QtCore.QRect(210, 260, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x17.setFont(font)
        self.label_x17.setObjectName("label_x17")

        self.IQ_spl = QtWidgets.QTextBrowser(self.centralwidget)
        self.IQ_spl.setGeometry(QtCore.QRect(233, 257, 60, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.IQ_spl.setFont(font)
        self.IQ_spl.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.IQ_spl.setObjectName("IQ_spl")

        self.label_b1 = QtWidgets.QLabel(self.centralwidget)
        self.label_b1.setGeometry(QtCore.QRect(20, 300, 410, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_b1.setFont(font)
        self.label_b1.setObjectName("label_b1")

        self.label_loadFat = QtWidgets.QLabel(self.centralwidget)
        self.label_loadFat.setGeometry(QtCore.QRect(17, 327, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_loadFat.setFont(font)
        self.label_loadFat.setObjectName("label_loadFat")

        self.loadfatmask = QtWidgets.QPushButton(self.centralwidget)
        self.loadfatmask.setGeometry(QtCore.QRect(330, 328, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.loadfatmask.setFont(font)
        self.loadfatmask.setObjectName("loadfatmask")

        self.cal_fat = QtWidgets.QPushButton(self.centralwidget)
        self.cal_fat.setGeometry(QtCore.QRect(330, 405, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.cal_fat.setFont(font)
        self.cal_fat.setObjectName("cal_fat")

        self.label_x18 = QtWidgets.QLabel(self.centralwidget)
        self.label_x18.setGeometry(QtCore.QRect(20, 365, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x18.setFont(font)
        self.label_x18.setObjectName("label_x18")

        self.label_x19 = QtWidgets.QLabel(self.centralwidget)
        self.label_x19.setGeometry(QtCore.QRect(210, 365, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x19.setFont(font)
        self.label_x19.setObjectName("label_x19")

        self.volume_vf = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_vf.setGeometry(QtCore.QRect(230, 362, 80, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_vf.setFont(font)
        self.volume_vf.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_vf.setObjectName("volume_vf")

        self.label_x20 = QtWidgets.QLabel(self.centralwidget)
        self.label_x20.setGeometry(QtCore.QRect(20, 405, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x20.setFont(font)
        self.label_x20.setObjectName("label_x20")

        self.label_x21 = QtWidgets.QLabel(self.centralwidget)
        self.label_x21.setGeometry(QtCore.QRect(210, 405, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x21.setFont(font)
        self.label_x21.setObjectName("label_x21")

        self.volume_tf = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_tf.setGeometry(QtCore.QRect(223, 402, 80, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_tf.setFont(font)
        self.volume_tf.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_tf.setObjectName("volume_vf")

        self.label_b2 = QtWidgets.QLabel(self.centralwidget)
        self.label_b2.setGeometry(QtCore.QRect(20, 445, 410, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_b2.setFont(font)
        self.label_b2.setObjectName("label_b2")

        self.label_loadVas = QtWidgets.QLabel(self.centralwidget)
        self.label_loadVas.setGeometry(QtCore.QRect(17, 472, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_loadVas.setFont(font)
        self.label_loadVas.setObjectName("label_loadVas")

        self.loadvasmask = QtWidgets.QPushButton(self.centralwidget)
        self.loadvasmask.setGeometry(QtCore.QRect(330, 473, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.loadvasmask.setFont(font)
        self.loadvasmask.setObjectName("loadvasmask")

        self.cal_vas = QtWidgets.QPushButton(self.centralwidget)
        self.cal_vas.setGeometry(QtCore.QRect(330, 735, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.cal_vas.setFont(font)
        self.cal_vas.setObjectName("cal_vas")

        self.label_x22 = QtWidgets.QLabel(self.centralwidget)
        self.label_x22.setGeometry(QtCore.QRect(20, 510, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x22.setFont(font)
        self.label_x22.setObjectName("label_x22")

        self.label_x23 = QtWidgets.QLabel(self.centralwidget)
        self.label_x23.setGeometry(QtCore.QRect(210, 510, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x23.setFont(font)
        self.label_x23.setObjectName("label_x21")

        self.area_PV = QtWidgets.QTextBrowser(self.centralwidget)
        self.area_PV.setGeometry(QtCore.QRect(230, 507, 80, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.area_PV.setFont(font)
        self.area_PV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.area_PV.setObjectName("area_PV")

        self.label_x24 = QtWidgets.QLabel(self.centralwidget)
        self.label_x24.setGeometry(QtCore.QRect(20, 555, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x24.setFont(font)
        self.label_x24.setObjectName("label_x24")

        self.label_x25 = QtWidgets.QLabel(self.centralwidget)
        self.label_x25.setGeometry(QtCore.QRect(210, 555, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x25.setFont(font)
        self.label_x25.setObjectName("label_x25")

        self.area_SV = QtWidgets.QTextBrowser(self.centralwidget)
        self.area_SV.setGeometry(QtCore.QRect(230, 552, 80, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.area_SV.setFont(font)
        self.area_SV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.area_SV.setObjectName("area_SV")

        self.label_x26 = QtWidgets.QLabel(self.centralwidget)
        self.label_x26.setGeometry(QtCore.QRect(20, 600, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x26.setFont(font)
        self.label_x26.setObjectName("label_x26")

        self.label_x27 = QtWidgets.QLabel(self.centralwidget)
        self.label_x27.setGeometry(QtCore.QRect(210, 600, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x27.setFont(font)
        self.label_x27.setObjectName("label_x27")

        self.area_LPV = QtWidgets.QTextBrowser(self.centralwidget)
        self.area_LPV.setGeometry(QtCore.QRect(230, 597, 80, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.area_LPV.setFont(font)
        self.area_LPV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.area_LPV.setObjectName("area_LPV")

        self.label_x28 = QtWidgets.QLabel(self.centralwidget)
        self.label_x28.setGeometry(QtCore.QRect(20, 645, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x28.setFont(font)
        self.label_x28.setObjectName("label_x28")

        self.label_x29 = QtWidgets.QLabel(self.centralwidget)
        self.label_x29.setGeometry(QtCore.QRect(210, 645, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x29.setFont(font)
        self.label_x29.setObjectName("label_x29")

        self.tortuosity_LPV = QtWidgets.QTextBrowser(self.centralwidget)
        self.tortuosity_LPV.setGeometry(QtCore.QRect(235, 642, 60, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.tortuosity_LPV.setFont(font)
        self.tortuosity_LPV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.tortuosity_LPV.setObjectName("tortuosity_LPV")

        self.label_x30 = QtWidgets.QLabel(self.centralwidget)
        self.label_x30.setGeometry(QtCore.QRect(20, 690, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x30.setFont(font)
        self.label_x30.setObjectName("label_x30")

        self.label_x31 = QtWidgets.QLabel(self.centralwidget)
        self.label_x31.setGeometry(QtCore.QRect(210, 690, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x31.setFont(font)
        self.label_x31.setObjectName("label_x31")

        self.curvature_SV = QtWidgets.QTextBrowser(self.centralwidget)
        self.curvature_SV.setGeometry(QtCore.QRect(235, 687, 60, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.curvature_SV.setFont(font)
        self.curvature_SV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.curvature_SV.setObjectName("curvature_SV")

        self.label_x32 = QtWidgets.QLabel(self.centralwidget)
        self.label_x32.setGeometry(QtCore.QRect(20, 735, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x32.setFont(font)
        self.label_x32.setObjectName("label_x31")

        self.label_x33 = QtWidgets.QLabel(self.centralwidget)
        self.label_x33.setGeometry(QtCore.QRect(210, 735, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_x33.setFont(font)
        self.label_x33.setObjectName("label_x33")

        self.curvature_LPV = QtWidgets.QTextBrowser(self.centralwidget)
        self.curvature_LPV.setGeometry(QtCore.QRect(235, 732, 60, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.curvature_LPV.setFont(font)
        self.curvature_LPV.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.curvature_LPV.setObjectName("curvature_LPV")


        self.volume_lm = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_lm.setGeometry(QtCore.QRect(177, 147, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_lm.setFont(font)
        self.volume_lm.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_lm.setObjectName("volume_lm")

        self.volume_sm = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_sm.setGeometry(QtCore.QRect(177, 277, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_sm.setFont(font)
        self.volume_sm.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_sm.setObjectName("volume_sp")


        self.distance = QtWidgets.QTextBrowser(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(147, 627, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.distance.setFont(font)
        self.distance.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.distance.setObjectName("distance")




        self.pic_box_vface = QtWidgets.QGroupBox(self.centralwidget)
        self.pic_box_vface.setGeometry(QtCore.QRect(861, 432, 404, 344))
        self.pic_box_vface.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0);')


        self.vtkWidget = QVTKRenderWindowInteractor(self.pic_box_vface)
        
        self.vtkWidget.setGeometry(QtCore.QRect(0, 0, 404, 344))
        self.ren = vtkRenderer()
        self.vtkWidget.GetRenderWindow().AddRenderer(self.ren)
        self.iren = self.vtkWidget.GetRenderWindow().GetInteractor()
        self.colors = vtkNamedColors()
        self.vtkpros = {}
        self.colors.SetColor('BkgColor', [0, 0, 0, 255])
        self.ren.SetBackground(self.colors.GetColor3d('BkgColor'))
        self.iren.Initialize()


        # Label "The Hazard Ratio:"
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1295, 700, 300, 30))
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # Box of "OHE risk:"
        self.plotresult = QtWidgets.QTextBrowser(self.centralwidget)
        self.plotresult.setGeometry(QtCore.QRect(1490, 698, 160, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.plotresult.setFont(font)


        self.plotresult.setAlignment(Qt.AlignCenter)
        #self.plotresult.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(100, 70, 90);')
        self.plotresult.setStyleSheet(
            'border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(222, 147, 122);')
        self.plotresult.setObjectName("plotresult")


        # Box of "Displayed Axial Slice:"
        self.page = QtWidgets.QLineEdit(self.centralwidget)
        #self.page.setGeometry(QtCore.QRect(350, 400, 70, 21))
        self.page.setGeometry(QtCore.QRect(780, 400, 70, 21))
        self.page.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page.setText("")
        self.page.setObjectName("page")

        # Box of "Displayed Coronal Slice:"
        self.page2 = QtWidgets.QLineEdit(self.centralwidget)
        #self.page2.setGeometry(QtCore.QRect(780, 915, 70, 21))
        self.page2.setGeometry(QtCore.QRect(780, 780, 70, 21))
        self.page2.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page2.setText("")
        self.page2.setObjectName("page2")

        # Box of "Displayed Sagittal Slice:"
        self.page3 = QtWidgets.QLineEdit(self.centralwidget)
        self.page3.setGeometry(QtCore.QRect(1200, 400, 70, 21))
        self.page3.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page3.setText("")
        self.page3.setObjectName("page3")


        # Label "Displayed Coronal Slice:"
        self.coronal_slice = QtWidgets.QLabel(self.centralwidget)
        self.coronal_slice.setGeometry(QtCore.QRect(631, 780, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.coronal_slice.setAlignment(QtCore.Qt.AlignRight)
        self.coronal_slice.setFont(font)
        self.coronal_slice.setObjectName("coronal_slice")

        # Label "Displayed Axial Slice:"
        self.axial_slice = QtWidgets.QLabel(self.centralwidget)
       # self.axial_slice.setGeometry(QtCore.QRect(280, 480, 151, 30))
        #self.axial_slice.setGeometry(QtCore.QRect(200, 400, 151, 30))
        self.axial_slice.setGeometry(QtCore.QRect(631, 400, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.axial_slice.setAlignment(QtCore.Qt.AlignRight)
        self.axial_slice.setFont(font)
        self.axial_slice.setObjectName("axial_slice")

        # Label "Displayed Sagittal Slice:"
        self.sagittal_slice = QtWidgets.QLabel(self.centralwidget)
        self.sagittal_slice.setGeometry(QtCore.QRect(1051, 400, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sagittal_slice.setAlignment(QtCore.Qt.AlignRight)
        self.sagittal_slice.setFont(font)
        self.sagittal_slice.setObjectName("sagittal_slice")

        # Label "Displayed coordinate:"
        self.coord = QtWidgets.QLabel(self.centralwidget)
        self.coord.setGeometry(QtCore.QRect(866, 780, 390, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.coord.setAlignment(QtCore.Qt.AlignRight)
        self.coord.setFont(font)
        self.coord.setObjectName("coord")

        # Label "Reference threshold: 0.157"
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1310, 740, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")


        # Button "Load liver segmentation"
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.loadcsv.clicked.connect(MainWindow.showclion)
        self.loadlivmask.clicked.connect(MainWindow.loadlivermaskf)
        self.loadfatmask.clicked.connect(MainWindow.loadfatmaskf)
        self.loadvasmask.clicked.connect(MainWindow.loadvasmaskf)
        self.predict.clicked.connect(MainWindow.predictf)
        self.radiomics.clicked.connect(MainWindow.radiomics_link)
        self.cal_liv.clicked.connect(MainWindow.cal_liver)
        self.cal_fat.clicked.connect(MainWindow.cal_fat_)
        self.cal_vas.clicked.connect(MainWindow.cal_vascular)

        self.clesarall.clicked.connect(MainWindow.clearallf)
        
        self.clearfactor.clicked.connect(MainWindow.clearfactorf)
        self.clincf_confirm.clicked.connect(MainWindow.clinicf_read)
        self.menu_image.triggered.connect(MainWindow.showpic)
        self.menu_seg.triggered.connect(MainWindow.show_mask)
        self.menu_liverseg.triggered.connect(MainWindow.liver_seg)
        self.menu_vascularseg.triggered.connect(MainWindow.vascular_seg)
        self.menu_musfatseg.triggered.connect(MainWindow.musfat_seg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OHE_Prediction"))
        self.predict.setText(_translate("MainWindow", "Start Prediction"))
        self.clesarall.setText(_translate("MainWindow", "Reload"))
        self.bound_predict.setText(_translate("MainWindow", "Prediction"))
        self.bound_predict2.setText(_translate("MainWindow", "Segmentation"))
        self.label_3.setText(_translate("MainWindow", "The Risk of OHE:"))

        self.axial_slice.setText(_translate("MainWindow", "Displayed axial slice:"))
        self.coronal_slice.setText(_translate("MainWindow", "Displayed coronal slice:"))
        self.sagittal_slice.setText(_translate("MainWindow", "Displayed sagittal slice:"))
        self.coord.setText(_translate("MainWindow", "Welcome to use! "))
        self.label_6.setText(_translate("MainWindow", "(The risk threshold is 0.35)"))

        self.label_calRadiomics.setText(_translate("MainWindow", "4. Calculate radiomics"))
        self.radiomics.setText(_translate("MainWindow", "Radiomics"))

        self.loadcsv.setText(_translate("MainWindow", "Load"))
        self.label_loadCli.setText(_translate("MainWindow", "5. Input clinical factors"))
        self.label__1.setText(_translate("MainWindow", "Load CSV file"))
        # self.label__2.setText(_translate("MainWindow", "Optaion(2)：Input clinical factors"))
        self.label__3.setText(_translate("MainWindow", "1.Age (Years)"))
        self.label__4.setText(_translate("MainWindow", "2.Sodium (mmol/L)"))
        self.label__5.setText(_translate("MainWindow", "3.ALT (U/L)"))
        self.label__6.setText(_translate("MainWindow", "4.Creatinine (μmol/L)"))
        self.label__7.setText(_translate("MainWindow", "5.ChildPugh score"))

        self.clincf_confirm.setText(_translate("MainWindow", "Confirm"))
        self.clearfactor.setText(_translate("MainWindow", "Clear"))

        self.label_loadLiver.setText(_translate("MainWindow", "1. Load liver and spleen mask"))
        self.label_loadFat.setText(_translate("MainWindow", "2. Load fat mask"))
        self.label_loadVas.setText(_translate("MainWindow", "3. Load vascular mask"))

        self.loadlivmask.setText(_translate("MainWindow", "Load"))
        self.cal_liv.setText(_translate("MainWindow", "Compute"))

        self.loadfatmask.setText(_translate("MainWindow", "Load"))
        self.cal_fat.setText(_translate("MainWindow", "Compute"))

        self.loadvasmask.setText(_translate("MainWindow", "Load"))
        self.cal_vas.setText(_translate("MainWindow", "Compute"))

        self.label_x10.setText(_translate("MainWindow", "Liver median:"))
        self.label_x11.setText(_translate("MainWindow", "___________"))
        self.label_x12.setText(_translate("MainWindow", "Spleen median:"))
        self.label_x13.setText(_translate("MainWindow", "___________"))
        self.label_x14.setText(_translate("MainWindow", "Liver IQ:"))
        self.label_x15.setText(_translate("MainWindow", "___________"))
        self.label_x16.setText(_translate("MainWindow", "Spleen IQ:"))
        self.label_x17.setText(_translate("MainWindow", "___________"))
        self.label_x18.setText(_translate("MainWindow", "Visceral fat volume:"))
        self.label_x19.setText(_translate("MainWindow", "___________"))
        self.label_x20.setText(_translate("MainWindow", "Total fat volume:"))
        self.label_x21.setText(_translate("MainWindow", "___________"))

        self.label_x22.setText(_translate("MainWindow", "PV maximum area:"))
        self.label_x23.setText(_translate("MainWindow", "___________"))
        self.label_x24.setText(_translate("MainWindow", "SV maximum area:"))
        self.label_x25.setText(_translate("MainWindow", "___________"))
        self.label_x26.setText(_translate("MainWindow", "LPV maximum area:"))
        self.label_x27.setText(_translate("MainWindow", "___________"))
        self.label_x28.setText(_translate("MainWindow", "LPV mean tortuosity:"))
        self.label_x29.setText(_translate("MainWindow", "___________"))
        self.label_x30.setText(_translate("MainWindow", "SV mean curvature:"))
        self.label_x31.setText(_translate("MainWindow", "___________"))
        self.label_x32.setText(_translate("MainWindow", "LPV mean curvature:"))
        self.label_x33.setText(_translate("MainWindow", "___________"))

        self.label_b1.setText(_translate("MainWindow", "----------------------------------------------------------"))
        self.label_b2.setText(_translate("MainWindow", "----------------------------------------------------------"))
        self.label_b3.setText(_translate("MainWindow", "----------------------------------------------------------"))
        self.label_b4.setText(_translate("MainWindow", "----------------------------------------------------------"))


class MyWindow1(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyWindow1, self).__init__()
        self.setupUi(self)
        self.img = None

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyleSheet(load_stylesheet(qt_api='pyqt5'))
    mw = MyWindow1()
    mw.show()
    sys.exit(app.exec_())